'use client';
import type { GraphEdgeData, GraphNodeData, PatientSpecificWarning } from '../types';
const meta: Record<GraphEdgeData['status'], { label: string; classes: string }> = {
  signal: { label: 'Interaction signal', classes: 'bg-rose-100 text-rose-700 hover:bg-rose-200' },
  no_evidence: { label: 'No documented signal found', classes: 'bg-emerald-100 text-emerald-700 hover:bg-emerald-200' },
  unavailable: { label: 'Source unavailable', classes: 'bg-slate-100 text-slate-500 hover:bg-slate-200' },
  extraction_failed: { label: 'Extraction unavailable', classes: 'bg-amber-100 text-amber-700 hover:bg-amber-200' },
};
export default function InteractionMatrix({nodes,edges,warnings,onSelect}:{nodes:GraphNodeData[];edges:GraphEdgeData[];warnings:PatientSpecificWarning[];onSelect:(edge:GraphEdgeData)=>void}) {
 const get=(a:string,b:string)=>edges.find(e=>(e.from===a&&e.to===b)||(e.from===b&&e.to===a));
 const hasWarning=(id:string)=>warnings.some(w=>w.medicationName.toLowerCase()===id.toLowerCase());
 return <section className="rounded-2xl border border-slate-200/80 bg-white/85 p-4 shadow-sm dark:border-slate-800 dark:bg-slate-900/85"><div><h2 className="font-bold">Interaction Matrix</h2><p className="text-xs text-slate-400">Click a cell to inspect its underlying evidence. Orange dot = patient-specific evidence.</p></div><div className="mt-4 overflow-x-auto"><table className="min-w-full border-separate border-spacing-1 text-center text-xs"><thead><tr><th className="min-w-24 text-left text-slate-400">Medication</th>{nodes.map(n=><th key={n.id} className="min-w-20 truncate font-semibold text-slate-600 dark:text-slate-300">{n.label}</th>)}</tr></thead><tbody>{nodes.map(row=><tr key={row.id}><th className="truncate text-left font-semibold text-slate-700 dark:text-slate-200">{row.label}{hasWarning(row.id)&&<span title="Patient-specific evidence" className="ml-1 text-amber-500">●</span>}</th>{nodes.map(col=>{if(row.id===col.id)return <td key={col.id} className="rounded-lg bg-slate-100 py-3 text-slate-400 dark:bg-slate-800">—</td>;const edge=get(row.id,col.id);if(!edge)return <td key={col.id} className="rounded-lg bg-slate-100 py-3 text-slate-400">—</td>;const m=meta[edge.status];return <td key={col.id}><button title={m.label} onClick={()=>onSelect(edge)} className={`w-full rounded-lg py-3 font-bold transition-colors ${m.classes}`}>{edge.status==='signal'?'🔴':edge.status==='no_evidence'?'🟢':edge.status==='extraction_failed'?'🟠':'•'}{(hasWarning(row.id)||hasWarning(col.id))&&edge.status!=='signal'&&<span className="ml-1 text-amber-500">●</span>}</button></td>})}</tr>)}</tbody></table></div><div className="mt-3 flex flex-wrap gap-3 text-[11px] text-slate-500"><span>🟢 No documented signal</span><span>🟠 Evidence unavailable / patient marker</span><span>🔴 Interaction signal</span><span>Gray = same medication</span></div></section>
}
