'use client';

import { useEffect, useMemo, useRef, useState } from 'react';
import { Bell, Check, Clock3, Pencil, Plus, Trash2, X } from 'lucide-react';
import type { MedicationSchedule as Schedule } from '../types';
type Log = { id: string; scheduleId: string; medicationName: string; date: string; status: 'taken' | 'missed' };
const SKEY='medgraph_schedules_v1', LKEY='medgraph_reminder_log_v1', FKEY='medgraph_reminder_fired_v1';
const today=()=>new Date().toISOString().slice(0,10);
const blank=():Schedule=>({id:crypto.randomUUID(),medicationName:'',dose:'',frequency:'once_daily',times:['08:00'],enabled:true});
const display=(time:string)=>new Date(`2000-01-01T${time}`).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'});
const defaults: Record<Exclude<Schedule['frequency'],'custom'>, string[]>={once_daily:['08:00'],twice_daily:['08:00','20:00'],three_times_daily:['08:00','14:00','20:00'],four_times_daily:['08:00','12:00','16:00','20:00']};
const count=(item:Schedule)=>item.frequency==='custom'?item.times.length:defaults[item.frequency].length;

export default function MedicationSchedule({medications}:{medications:string[]}) {
 const [items,setItems]=useState<Schedule[]>([]); const [logs,setLogs]=useState<Log[]>([]); const [due,setDue]=useState<Schedule[]>([]); const [draft,setDraft]=useState<Schedule|null>(null); const [permission,setPermission]=useState<NotificationPermission|'unsupported'>('default'); const [note,setNote]=useState(''); const audio=useRef<AudioContext|null>(null);
 useEffect(()=>{try{setItems(JSON.parse(localStorage.getItem(SKEY)||'[]'));setLogs(JSON.parse(localStorage.getItem(LKEY)||'[]'))}catch{}setPermission('Notification'in window?Notification.permission:'unsupported')},[]);
 useEffect(()=>{localStorage.setItem(SKEY,JSON.stringify(items))},[items]); useEffect(()=>{localStorage.setItem(LKEY,JSON.stringify(logs))},[logs]);
 const ring=()=>{const ctx=audio.current;if(!ctx||ctx.state!=='running')return;[0,.22,.44].forEach(delay=>{const osc=ctx.createOscillator(),gain=ctx.createGain();osc.frequency.value=880;gain.gain.setValueAtTime(.07,ctx.currentTime+delay);gain.gain.exponentialRampToValueAtTime(.001,ctx.currentTime+delay+.18);osc.connect(gain);gain.connect(ctx.destination);osc.start(ctx.currentTime+delay);osc.stop(ctx.currentTime+delay+.2)})};
 const enable=async()=>{if(!('Notification'in window)){setPermission('unsupported');setNote('This browser does not support notifications.');return}try{const Ctor=window.AudioContext||(window as Window & {webkitAudioContext?:typeof AudioContext}).webkitAudioContext;if(Ctor){audio.current=new Ctor();await audio.current.resume()}const granted=await Notification.requestPermission();setPermission(granted);setNote(granted==='granted'?'Notifications and reminder sound are enabled.':granted==='denied'?'Notifications are blocked. Enable them in browser site settings.':'Notification permission was not granted.')}catch{setNote('Unable to request notification permission. Check browser settings.')}};
 useEffect(()=>{if(permission!=='granted')return;const check=()=>{const now=new Date(),date=now.toISOString().slice(0,10),time=now.toTimeString().slice(0,5);let fired:Record<string,boolean>={};try{fired=JSON.parse(localStorage.getItem(FKEY)||'{}')}catch{}const fresh=items.filter(i=>i.enabled&&i.times.includes(time)&&(!i.startDate||i.startDate<=date)&&(!i.endDate||i.endDate>=date)&&!fired[`${date}:${time}:${i.id}`]);if(!fresh.length)return;fresh.forEach(i=>fired[`${date}:${time}:${i.id}`]=true);localStorage.setItem(FKEY,JSON.stringify(fired));setDue(old=>[...old,...fresh.filter(i=>!old.some(x=>x.id===i.id))]);ring();const body=fresh.map(i=>`${i.medicationName}${i.dose?` — ${i.dose}`:''}`).join(', ');new Notification('Medication Reminder',{body:`Time to take: ${body}`})};check();const timer=setInterval(check,15000);return()=>clearInterval(timer)},[items,permission]);
 const record=(item:Schedule,status:Log['status'])=>{setLogs(old=>[...old,{id:crypto.randomUUID(),scheduleId:item.id,medicationName:item.medicationName,date:today(),status}]);setDue(old=>old.filter(x=>x.id!==item.id))};
 const save=()=>{if(!draft?.medicationName.trim()||!draft.times.length||draft.times.some(t=>!/^\d{2}:\d{2}$/.test(t))){setNote('Enter a medication and valid times in HH:MM format.');return}setItems(old=>old.some(i=>i.id===draft.id)?old.map(i=>i.id===draft.id?draft:i):[...old,draft]);setDraft(null)};
 const timeline=useMemo(()=>items.filter(i=>i.enabled).flatMap(i=>i.times.map(time=>({time,item:i}))).sort((a,b)=>a.time.localeCompare(b.time)),[items]);const responses=logs.filter(l=>l.date===today()),taken=responses.filter(l=>l.status==='taken').length,total=responses.length+due.length,rate=total?Math.round(taken/total*100):0; const field='w-full rounded-lg border border-slate-200 bg-white px-2.5 py-2 text-sm outline-none focus:border-blue-500 dark:border-slate-700 dark:bg-slate-900';
 return <section className="rounded-2xl border border-slate-200/80 bg-white/85 p-4 shadow-sm dark:border-slate-800 dark:bg-slate-900/85"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="flex items-center gap-2 font-bold"><Clock3 className="h-4 w-4 text-blue-600"/>Medication Schedule</h2><p className="text-xs text-slate-400">Set a time, enable notifications, then mark each alert taken or missed.</p></div><div className="flex gap-2"><button onClick={enable} className="rounded-lg border border-blue-200 bg-blue-50 px-3 py-2 text-xs font-semibold text-blue-700"><Bell className="mr-1 inline h-3.5 w-3.5"/>{permission==='granted'?'Notifications enabled':'Enable notifications'}</button><button onClick={()=>setDraft(blank())} className="rounded-lg bg-blue-600 px-3 py-2 text-xs font-semibold text-white"><Plus className="mr-1 inline h-3.5 w-3.5"/>Add schedule</button></div></div>{note&&<p className={`mt-3 rounded-lg p-2 text-xs ${permission==='granted'?'bg-emerald-50 text-emerald-800':'bg-amber-50 text-amber-800'}`}>{note}</p>}
 {due.length>0&&<div className="mt-4 rounded-xl border border-blue-200 bg-blue-50 p-3"><b className="text-sm text-blue-900">Medication reminder</b>{due.map(i=><div key={i.id} className="mt-2 flex flex-wrap items-center justify-between gap-2 rounded-lg bg-white p-2 text-sm"><span>💊 <b>{i.medicationName}</b>{i.dose?` — ${i.dose}`:''}</span><span className="flex gap-2"><button onClick={()=>record(i,'taken')} className="rounded-md bg-emerald-600 px-2 py-1 text-xs font-bold text-white"><Check className="mr-1 inline h-3 w-3"/>Taken</button><button onClick={()=>record(i,'missed')} className="rounded-md bg-rose-600 px-2 py-1 text-xs font-bold text-white"><X className="mr-1 inline h-3 w-3"/>Missed</button></span></div>)}</div>}
 {draft&&<div className="mt-4 grid gap-2 rounded-xl bg-slate-50 p-3 md:grid-cols-3 dark:bg-slate-800"><input className={field} list="med-list" placeholder="Medication" value={draft.medicationName} onChange={e=>setDraft({...draft,medicationName:e.target.value})}/><datalist id="med-list">{medications.map(m=><option key={m} value={m}/>)}</datalist><input className={field} placeholder="Dose, e.g. 5 mg" value={draft.dose} onChange={e=>setDraft({...draft,dose:e.target.value})}/><select className={field} value={draft.frequency} onChange={e=>{const frequency=e.target.value as Schedule['frequency'];setDraft({...draft,frequency,times:frequency==='custom'?draft.times:defaults[frequency]})}}>{[['once_daily','Once daily'],['twice_daily','Twice daily'],['three_times_daily','Three times daily'],['four_times_daily','Four times daily'],['custom','Custom']].map(([v,l])=><option key={v} value={v}>{l}</option>)}</select><div className="md:col-span-2"><label className="text-xs">Times (24-hour, comma-separated)</label><input className={field} value={draft.times.join(', ')} onChange={e=>setDraft({...draft,times:e.target.value.split(',').map(t=>t.trim()).filter(Boolean)})} placeholder="08:00, 20:00"/></div><div className="flex gap-2"><button onClick={save} className="rounded-lg bg-blue-600 px-3 py-2 text-xs font-bold text-white">Save</button><button onClick={()=>setDraft(null)} className="text-xs">Cancel</button></div></div>}
 <div className="mt-4 overflow-x-auto"><table className="w-full text-left text-sm"><thead className="text-xs text-slate-400"><tr><th>Medication</th><th>Dose</th><th>Frequency</th><th>Times</th><th>Actions</th></tr></thead><tbody>{items.map(i=><tr key={i.id} className="border-t border-slate-100 dark:border-slate-800"><td className="py-2 font-semibold">{i.medicationName}</td><td>{i.dose||'—'}</td><td>{i.frequency.replaceAll('_',' ')}</td><td>{i.times.map(display).join(', ')}</td><td><button onClick={()=>setDraft(i)}><Pencil className="inline h-3.5 w-3.5"/></button><button onClick={()=>setItems(old=>old.filter(x=>x.id!==i.id))} className="ml-3 text-rose-500"><Trash2 className="inline h-3.5 w-3.5"/></button></td></tr>)}</tbody></table></div>
 <div className="mt-4 grid gap-3 lg:grid-cols-2"><div className="rounded-xl bg-blue-50/60 p-3"><h3 className="text-xs font-bold text-blue-800">Daily Timeline</h3>{timeline.length?timeline.map(({time,item})=><div key={`${time}-${item.id}`} className="mt-2 flex gap-3 text-sm"><span className="w-16 font-mono text-blue-700">{display(time)}</span><span>💊 <b>{item.medicationName}</b>{item.dose?` — ${item.dose}`:''}</span></div>):<p className="mt-1 text-xs text-slate-500">No active scheduled medication.</p>}</div><div className="rounded-xl border border-emerald-100 bg-emerald-50/60 p-3"><h3 className="text-xs font-bold text-emerald-800">Medication Alertness</h3><div className="mt-3 flex items-center gap-4"><div className="flex h-20 w-20 items-center justify-center rounded-full text-lg font-extrabold text-emerald-700" style={{background:`conic-gradient(#10b981 ${rate*3.6}deg,#d1fae5 0deg)`}}><span className="rounded-full bg-white px-2 py-4">{rate}%</span></div><p className="text-sm text-slate-600"><b>{taken}</b> taken out of <b>{total}</b> responded or due alerts today.<br/><span className="text-xs">Mark each reminder to keep this record accurate.</span></p></div></div></div>
 <div className="mt-4 rounded-xl border border-slate-200 p-3"><h3 className="text-xs font-bold text-slate-700">Medication Frequency</h3>{items.length?items.map(i=><div key={`freq-${i.id}`} className="mt-2 grid grid-cols-[110px_1fr_48px] items-center gap-2 text-xs"><span className="truncate font-medium">{i.medicationName}</span><div className="h-3 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full bg-blue-600" style={{width:`${Math.min(100,count(i)*25)}%`}}/></div><span>{count(i)}/day</span></div>):<p className="mt-1 text-xs text-slate-500">Add a schedule to view frequency.</p>}</div></section>
}
